# Configuration Details:
# Note: The details are only to guide if there are any issues
# The passwords and usersnames should be updated with the required ones

# NextCLoud with MariaDB/MySQL all behind Nginx acting as a Reverse Proxy with SSL Encryption from LetsEcrypt.
#
# During initial NextCLoud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: nextcloud 
# Database password: nextcloud
# Database name: nextcloud
# Database host: replace "localhost" with "db" the same name as the data base container name.

# The overwriteprotocol needs to be changed in ./app/config/config.php

#'installed' => true,
#'overwriteprotocol' => 'https',
#'app_install_overwrite' => 
#array (
#  0 => 'uploaddetails',

# If issues appear:
#systemctl stop docker.socket
#  systemctl stop docker
#  systemctl status docker
#  rm -rf /var/lib/docker/
#  systemctl start docker.socket
#  systemctl start docker

# How filestructure should look like:
# drwxr-xr-x 6 www-data         www-data 4096 Apr  3 09:15 app
# drwxr-xr-x 6 root             root     4096 Apr  3 09:19 proxy
# drwxr-xr-x 5 systemd-coredump root     4096 Apr  3 09:37 db

version: '3' 

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 35653:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw     # Update ./proxy with location you need volumes mapped at
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw   # Update ./proxy with location you need volumes mapped at
      - ./proxy/html:/usr/share/nginx/html:rw   # Update ./proxy with location you need volumes mapped at
      - ./proxy/certs:/etc/nginx/certs:ro       # Update ./proxy with location you need volumes mapped at
      - ./proxy/conf.d/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf  # Update ./proxy with location you need volumes mapped at
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw       # Update ./proxy with location you need volumes mapped at
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw   # Update ./proxy with location you need volumes mapped at
      - ./proxy/html:/usr/share/nginx/html:rw   # Update ./proxy with location you need volumes mapped at
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - ./db:/var/lib/mysql   # Update ./db with location you need volumes mapped at
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD={PASSWORD}
      - MYSQL_PASSWORD={PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config           # Update ./app with location you need volumes mapped at
      - ./app/custom_apps:/var/www/html/custom_apps # Update ./app with location you need volumes mapped at
      - ./app/data:/var/www/html/data               # Update ./app with location you need volumes mapped at
      - ./app/themes:/var/www/html/themes           # Update ./app with location you need volumes mapped at
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=lastpengu.duckdns.org
      - LETSENCRYPT_HOST=lastpengu.duckdns.org
      - LETSENCRYPT_EMAIL=lenny@dude.net
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network: