# Note: This playbook works only for debian servers

# This playbook is for package updates on remote servers
# To run this playbook use:
# ansible-playbook -i /ansible/inventory/hosts $HOME/$USERNAME/playbooks/apt.yml --key-file $HOME/.ssh/$KEYNAME

# Initial Environment:
- hosts: debian
  name: Maintain Systems
  remote_user: $USERNAME
  become: yes
  tasks:

# To run this: ansible-playbook -i /ansible/inventory/hosts /ansible/playbooks/system_update.yml --key-file $HOME/$USERNAME/.ssh/$KEYNAME --tags upgrade
    - name: apt upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
      tags: upgrade
    
# To run this: ansible-playbook -i /ansible/inventory/hosts /ansible/playbooks/system_update.yml --key-file $HOME/$USERNAME/.ssh/$KEYNAME --tags dist
    - name: apt upgrade
      apt:
        update_cache: yes
        upgrade: 'dist'
      tags: dist


#  To run this: ansible-playbook -i /ansible/inventory/hosts /ansible/playbooks/system_update.yml --key-file $HOME/$USERNAME/.ssh/$KEYNAME --tags install
    - name: Install required Packages
      apt:
        state: present
        name:
          - sudo
          - unattended-upgrades
          - apt-listchanges
          - vim
          - curl
          - wget
          - ufw
          - fail2ban
          - acl
          - net-tools
      tags: install